import 'package:moodiary_i18n/moodiary_i18n.dart';
import 'package:moodiary_models/moodiary_models.dart';
import 'package:mui/mui.dart';

abstract class AppColor {
  static const Color moodPositive = Color(0xFF2EB872);
  static const Color moodNeutral = Color(0xFF8A9099);
  static const Color moodNegative = Color(0xFFFA4659);
  static const Color moodFulfilled = Color(0xFFF97316);
  static const Color moodAngry = Color(0xFFDC2626);
  static const Color moodAnxious = Color(0xFF7C3AED);
  static const Color moodTired = Color(0xFF64748B);
  static const Color moodSpeechless = Color(0xFF78716C);
  static const Color moodLove = Color(0xFFEC4899);
  static const Color moodStudy = Color(0xFF3B82F6);
  static const Color moodSlacking = Color(0xFF14B8A6);
  static const Color moodFood = Color(0xFFCA8A04);
  static const Color moodWork = Color(0xFF8D6E63);
  static const Color moodTravel = Color(0xFF0EA5E9);
  static const Color moodSports = Color(0xFF65A30D);
  static const Color moodSick = Color(0xFFBA68C8);
  static const Color moodRelaxed = Color(0xFF22C55E);
  static const Color moodGrateful = Color(0xFFD97706);
  static const Color moodLonely = Color(0xFF6366F1);
  static const Color moodCelebrating = Color(0xFFD946EF);
  static const Color moodFocused = Color(0xFF2563EB);
  static const Color moodMeeting = Color(0xFF0891B2);
  static const Color moodOvertime = Color(0xFFEA580C);
  static const Color moodCommuting = Color(0xFF475569);
  static const Color moodSleep = Color(0xFF7E57C2);
  static const Color moodCoffee = Color(0xFFA16207);
  static const Color moodHome = Color(0xFF059669);
  static const Color moodShopping = Color(0xFFDB2777);
  static const Color moodCooking = Color(0xFFC2410C);
  static const Color moodGaming = Color(0xFF9333EA);
  static const Color moodMusic = Color(0xFFE11D48);
  static const Color moodMovie = Color(0xFF4F46E5);
  static const Color moodExcited = Color(0xFFF59E0B);
  static const Color moodExpectant = Color(0xFF06B6D4);
  static const Color moodProud = Color(0xFFB45309);
  static const Color moodRelieved = Color(0xFF0D9488);
  static const Color moodHurt = Color(0xFFA21CAF);
  static const Color moodDisappointed = Color(0xFF5B7393);
  static const Color moodIrritated = Color(0xFFF43F5E);
  static const Color moodConfused = Color(0xFF7373B3);
}

extension DiaryMoodVisuals on DiaryMood {
  /// Face emoji for current moods; historical activities keep their icons.
  String? get emoji => switch (this) {
    .positive => '😊',
    .neutral => '😐',
    .negative => '😔',
    .fulfilled => '😁',
    .angry => '😠',
    .anxious => '😰',
    .tired => '😩',
    .speechless => '😑',
    .love => '🥰',
    .relaxed => '😌',
    .grateful => '🥹',
    .lonely => '🥲',
    .excited => '😆',
    .expectant => '🤩',
    .proud => '😎',
    .relieved => '😮‍💨',
    .hurt => '🥺',
    .disappointed => '😞',
    .irritated => '😤',
    .confused => '😕',
    _ => null,
  };

  Color get color => switch (this) {
    .positive => AppColor.moodPositive,
    .neutral => AppColor.moodNeutral,
    .negative => AppColor.moodNegative,
    .fulfilled => AppColor.moodFulfilled,
    .angry => AppColor.moodAngry,
    .anxious => AppColor.moodAnxious,
    .tired => AppColor.moodTired,
    .speechless => AppColor.moodSpeechless,
    .love => AppColor.moodLove,
    .study => AppColor.moodStudy,
    .slacking => AppColor.moodSlacking,
    .food => AppColor.moodFood,
    .work => AppColor.moodWork,
    .travel => AppColor.moodTravel,
    .sports => AppColor.moodSports,
    .sick => AppColor.moodSick,
    .relaxed => AppColor.moodRelaxed,
    .grateful => AppColor.moodGrateful,
    .lonely => AppColor.moodLonely,
    .celebrating => AppColor.moodCelebrating,
    .focused => AppColor.moodFocused,
    .meeting => AppColor.moodMeeting,
    .overtime => AppColor.moodOvertime,
    .commuting => AppColor.moodCommuting,
    .sleep => AppColor.moodSleep,
    .coffee => AppColor.moodCoffee,
    .home => AppColor.moodHome,
    .shopping => AppColor.moodShopping,
    .cooking => AppColor.moodCooking,
    .gaming => AppColor.moodGaming,
    .music => AppColor.moodMusic,
    .movie => AppColor.moodMovie,
    .excited => AppColor.moodExcited,
    .expectant => AppColor.moodExpectant,
    .proud => AppColor.moodProud,
    .relieved => AppColor.moodRelieved,
    .hurt => AppColor.moodHurt,
    .disappointed => AppColor.moodDisappointed,
    .irritated => AppColor.moodIrritated,
    .confused => AppColor.moodConfused,
  };

  IconData get icon => switch (this) {
    .positive => LucideIcons.smile,
    .neutral => LucideIcons.meh,
    .negative => LucideIcons.frown,
    .fulfilled => LucideIcons.sparkles,
    .angry => LucideIcons.angry,
    .anxious => LucideIcons.tornado,
    .tired => LucideIcons.batteryLow,
    .speechless => LucideIcons.annoyed,
    .love => LucideIcons.heart,
    .study => LucideIcons.bookOpen,
    .slacking => LucideIcons.fish,
    .food => LucideIcons.utensils,
    .work => LucideIcons.briefcase,
    .travel => LucideIcons.plane,
    .sports => LucideIcons.dumbbell,
    .sick => LucideIcons.thermometer,
    .relaxed => LucideIcons.leaf,
    .grateful => LucideIcons.handHeart,
    .lonely => LucideIcons.cloudRain,
    .celebrating => LucideIcons.partyPopper,
    .focused => LucideIcons.target,
    .meeting => LucideIcons.users,
    .overtime => LucideIcons.clock,
    .commuting => LucideIcons.trainFront,
    .sleep => LucideIcons.moon,
    .coffee => LucideIcons.coffee,
    .home => LucideIcons.house,
    .shopping => LucideIcons.shoppingBag,
    .cooking => LucideIcons.chefHat,
    .gaming => LucideIcons.gamepad2,
    .music => LucideIcons.music,
    .movie => LucideIcons.clapperboard,
    .excited => LucideIcons.zap,
    .expectant => LucideIcons.sunrise,
    .proud => LucideIcons.award,
    .relieved => LucideIcons.wind,
    .hurt => LucideIcons.heartCrack,
    .disappointed => LucideIcons.cloudDrizzle,
    .irritated => LucideIcons.flame,
    .confused => LucideIcons.circleQuestionMark,
  };

  String get iconName => switch (this) {
    .positive => 'smile',
    .neutral => 'meh',
    .negative => 'frown',
    .fulfilled => 'sparkles',
    .angry => 'angry',
    .anxious => 'tornado',
    .tired => 'battery-low',
    .speechless => 'annoyed',
    .love => 'heart',
    .study => 'book-open',
    .slacking => 'fish',
    .food => 'utensils',
    .work => 'briefcase',
    .travel => 'plane',
    .sports => 'dumbbell',
    .sick => 'thermometer',
    .relaxed => 'leaf',
    .grateful => 'hand-heart',
    .lonely => 'cloud-rain',
    .celebrating => 'party-popper',
    .focused => 'target',
    .meeting => 'users',
    .overtime => 'clock',
    .commuting => 'train-front',
    .sleep => 'moon',
    .coffee => 'coffee',
    .home => 'house',
    .shopping => 'shopping-bag',
    .cooking => 'chef-hat',
    .gaming => 'gamepad-2',
    .music => 'music',
    .movie => 'clapperboard',
    .excited => 'zap',
    .expectant => 'sunrise',
    .proud => 'award',
    .relieved => 'wind',
    .hurt => 'heart-crack',
    .disappointed => 'cloud-drizzle',
    .irritated => 'flame',
    .confused => 'circle-question-mark',
  };

  String label(BuildContext context) => labelOf(context.l10n);

  String labelOf(Translations l10n) => switch (this) {
    .positive => l10n.common.moodPositive,
    .neutral => l10n.common.moodNeutral,
    .negative => l10n.common.moodNegative,
    .fulfilled => l10n.common.moodFulfilled,
    .angry => l10n.common.moodAngry,
    .anxious => l10n.common.moodAnxious,
    .tired => l10n.common.moodTired,
    .speechless => l10n.common.moodSpeechless,
    .love => l10n.common.moodLove,
    .study => l10n.common.moodStudy,
    .slacking => l10n.common.moodSlacking,
    .food => l10n.common.moodFood,
    .work => l10n.common.moodWork,
    .travel => l10n.common.moodTravel,
    .sports => l10n.common.moodSports,
    .sick => l10n.common.moodSick,
    .relaxed => l10n.common.moodRelaxed,
    .grateful => l10n.common.moodGrateful,
    .lonely => l10n.common.moodLonely,
    .celebrating => l10n.common.moodCelebrating,
    .focused => l10n.common.moodFocused,
    .meeting => l10n.common.moodMeeting,
    .overtime => l10n.common.moodOvertime,
    .commuting => l10n.common.moodCommuting,
    .sleep => l10n.common.moodSleep,
    .coffee => l10n.common.moodCoffee,
    .home => l10n.common.moodHome,
    .shopping => l10n.common.moodShopping,
    .cooking => l10n.common.moodCooking,
    .gaming => l10n.common.moodGaming,
    .music => l10n.common.moodMusic,
    .movie => l10n.common.moodMovie,
    .excited => l10n.common.moodExcited,
    .expectant => l10n.common.moodExpectant,
    .proud => l10n.common.moodProud,
    .relieved => l10n.common.moodRelieved,
    .hurt => l10n.common.moodHurt,
    .disappointed => l10n.common.moodDisappointed,
    .irritated => l10n.common.moodIrritated,
    .confused => l10n.common.moodConfused,
  };
}

extension ManualWeatherLabel on ManualWeather {
  String label(BuildContext context) => labelOf(context.l10n);

  String labelOf(Translations l10n) => switch (this) {
    .sunny => l10n.common.weatherSunny,
    .cloudy => l10n.common.weatherCloudy,
    .overcast => l10n.common.weatherOvercast,
    .showerRain => l10n.common.weatherShowerRain,
    .lightRain => l10n.common.weatherLightRain,
    .moderateRain => l10n.common.weatherModerateRain,
    .heavyRain => l10n.common.weatherHeavyRain,
    .storm => l10n.common.weatherStorm,
    .thundershower => l10n.common.weatherThundershower,
    .lightSnow => l10n.common.weatherLightSnow,
    .heavySnow => l10n.common.weatherHeavySnow,
    .sleet => l10n.common.weatherSleet,
    .foggy => l10n.common.weatherFoggy,
    .haze => l10n.common.weatherHaze,
    .hot => l10n.common.weatherHot,
    .cold => l10n.common.weatherCold,
  };
}
